myapp/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [

    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    path('home/', include('pracice.urls')),


]

pracice/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'pracice'

urlpatterns = [
    path('', views.HomePage.as_view(), name='homepage'),
    #path('', views.add_book(), name='homepage'),
    #/book/id/
    path('<pk>/', views.DetailView.as_view(), name='detail'),
    path('add_book/', views.add_book, name="add_book"),
]

pracice/models.py
from django.db import models

class Author(models.Model):
    author_name = models.CharField(max_length=200)
    author_id = models.EmailField(max_length=200)
    #genre = models.CharField(max_length=100)

    def __str__(self):
        return self.author_name

class Book(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    book_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    language = models.CharField(max_length=50)

    def __str__(self):
        return self.book_title

pracice/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from django.template import loader
from .models import Author, Book
from django.views import generic

class HomePage(generic.ListView):
    template_name = 'pracice/home.html'

    def get_queryset(self):
        return Book.objects.all()


class DetailView(generic.DetailView):
    model = Book
    template_name = 'pracice/detail.html'


def add_book(request):
    if request.method == "POST":
        book_title = request.POST['book_title']
        author = request.POST['author']
        genre = request.POST['genre']
        language = request.POST['language']

        books = Book.objects.create(book_title=book_title, author=author, genre=genre, language=language)
        books.save()
        alert = True
        return render(request, 'pracice/add_book.html', {'alert': alert})
    return render(request, 'pracice/add_book.html')

"""
def detail(request,book_id):
    #book = get_object_or_404(Book, pk=book_id)
    try:
        book = Book.objects.get(pk=book_id)
    except Book.DoesNotExist:
        raise Http404("Book is not present in the library")
    
    return render(request, 'pracice/detail.html', {'book': book})
"""

pracice/templates/pracice/add_book.html
{% extends 'pracice/base.html' %}

{% block body %}

<div class="container">
    <form method="POST"> {% csrf_token %}
    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Book Name</i></label>
            <input type="text" class="form-control mt-2" name="book_title" placeholder="Enter name of the Book" required>
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Author Name</i></label>
            <input type="text" class="form-control mt-2" name="author" placeholder="Enter name of the Author" required>
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Genre</i></label>
            <input type="number" class="form-control mt-2" name="genre" placeholder="Enter genre of the book" required>
        </div>
    </div>

    <div class="row mt-4">
        <div class="form-group col-md-12">
            <label><i style="font-weight: bold;">Language</i></label>
            <input type="text" class="form-control mt-2" name="language" placeholder="Enter language of the book" required>
        </div>
    </div>
    <button type="submit" class="btn btn-outline-primary mt-4">Add Book</button>
        </form>
</div>

pracice/templates/pracice/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LIBRARY</title>
    {% load static %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'pracice/style.css' %}" />
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'pracice:homepage' %}">Library</a>
        </div>

        <!--items in navbar -->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{%url 'pracice:homepage' %}">
                        <span class="glyphicon glyphicon-book" area-hidden="true"></span>&nbsp;ABOUT
                    </a>
                </li>
                <li>
                    <a href="{%url 'pracice:homepage' %}">DONATE</a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search Book</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user" area-hidden="true"></span> Sign Up</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-in" area-hidden="true"></span> Login</a></li>
            </ul>

        </div>

    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

pracice/templates/pracice/detail.html
{% extends 'pracice/base.html' %}


{% block body %}
<h1>Details of the Book - {{ book.book_title }} </h1>
<ul>
  <li>Author - {{ book.author }} </li>
  <li>Genre - {{ book.genre }}</li>
  <li>Language - {{ book.language }}</li>
</ul>
{% endblock %}

pracice/templates/pracice/home.html
{% extends 'pracice/base.html' %}

{% block body %}

<h2>Books List</h2><br>
<ul>
    {% for book in object_list %}
    <li>
        <a href="{% url 'pracice:detail' book.id %}">{{ book.book_title }}</a>
    </li>
    {% endfor %}
</ul>


{% endblock %}